version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb_data:
