name: Deployment

on:
  push:
    branches:
      - deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log a Message
        run: echo "Code has been successfully checked out and this message is logged!"
